# Generated by Django 5.2.4 on 2025-07-28 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('specialties', models.CharField(help_text='e.g. Property Law, Family Law', max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('languages', models.CharField(help_text='e.g. English, Urdu', max_length=255)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Consultation fee in PKR', max_digits=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
